### ISSUE TITLE
Feature Request: OPDS: серии в карточке книги

### ISSUE THREAD

**Issue by AlexeyTorch** [zlsl/flibusta#16]
при просмотре каталога  opds alreader  оригинальном  OPDS флибусты при открытии карточки книги можно увидеть ссылку на серию, и перейти  на нее (скрин Flibusta.png)
В этом контейнере при открытии карточки  ссылок  на серию / автора нет. (та те книга,  скрин Docker.png)

Можно попросить добавить в opds аналогичный sункционал
![Docker](https://github.com/user-attachments/assets/e6055f09-c161-4208-a5a0-bc696c3f1fe0)
![Flibusta](https://github.com/user-attachments/assets/da2caaba-df6c-4ca4-9695-fe3242d0f3cb)

**Comment by zlsl** [comment]
Код в репозитории - примерно 6-7 лет назад обновлялся. А релизация OPDS в каждом устройстве своеобразная, попробую добавить, но тестировать особо не на чём.

Сейчас в разработке и использовании библиотечная система система с возможностью добавления, каталогизации своих книг, авторов и прочего. С уже четким разделением бэка и фронта, модульная. 

Код в данной версии обновляю, когда есть время.

**Comment by DmitriyStoyanov** [comment]
Подготовил ПР который данный функционал добавляет

**Comment by AlexeyTorch** [comment]
> Подготовил ПР который данный функционал добавляет

Да,  спасибо,  кроме серии и автора, в этой версии перестал падать AlReaderX  при просмотре списка авторов.

**Comment by DmitriyStoyanov** [comment]
[like]  Dmitry Stoyanov reacted to your message:
________________________________
