### ISSUE TITLE
Не работает инициализация

### ISSUE THREAD

**Issue by abubaca4** [zlsl/flibusta#2]
При попытке инициализации в логах php 
`NOTICE: PHP message: PHP Warning:  file_get_contents(/application/sql/status): failed to open stream: No such file or directory in /application/modules/service/index.php on line 77`
Файла там действительно нет но сама папка в наличии
Все 3 контейнера успешно поднялись
Из изменений
Поменял путь к /application/flibusta на свой в docker-compose(в обоих местах)
Удалил из db .gitkeep тк с ним база не инициализировалась

Ещё вопрос 
Можно ли использовать не полный дамп а только fb2 дамп

Хорошо бы как то предусмотреть вариант запуска в котором в контейнере только само приложение php а web сервер и база данных используются уже существующие на хосте
Возможно в настройки nginx по умолчанию стоит ограничить количество worker до 1го, остальные избыточны(как мне кажется в данном случае)

**Comment by meugr** [comment]
Привет!
Файл `/application/modules/service/index.php` есть в репозитории. Видимо, ты его случайно удалил. 
Подсунул fb2 дамп с рутрекера - все работает. 

Кстати для потомков - ссылка на скачивание [FlibustaSQL](http://meugr.quickconnect.to/d/s/10GMyJFb1pMxNC9KeCwMV3y4AajJteaC/82FUjO5uhjdcnd6My5Ws8UTYUP0GJBrf-v7sAkD19sgs) директории по состоянию на сегодня, так как flibustа.is работает нестабильно.

**Comment by abubaca4** [comment]
Да есть у меня index.php
ls application/modules/service/
index.php  module.conf
Судя по ошибке отсутствует /application/sql/status
и у меня действительно папка sql пустая в ней ничего нет
при этом в логах контейнера c postgres ошибок нет. а в логах контейнера с php первая ошибка на эту тему приведена выше

**Comment by meugr** [comment]
Возможно, нет прав на запись?
`Каталоги FlibustaSQL, cache и их подкаталоги должны иметь права на запись для контейнера.`
Впрочем, без прав на запись у меня все запустилось, права мешали обновлению базы из меню сервиса.

**Comment by abubaca4** [comment]
В итоге с chmod -R 777 процесс запустился, до этого пытался выдать более конкретные права
оказывается оно ещё само gz распаковывает а я думал что дело в этом и распаковал через 
for f in *.gz ; do gunzip -c "$f" > FlibustaSQL/"${f%.*}" ; done

**Comment by zlsl** [comment]
> При попытке инициализации в логах php `NOTICE: PHP message: PHP Warning: file_get_contents(/application/sql/status): failed to open stream: No such file or directory in /application/modules/service/index.php on line 77` Файла там действительно нет но сама папка в наличии Все 3 контейнера успешно поднялись Из изменений Поменял путь к /application/flibusta на свой в docker-compose(в обоих местах) Удалил из db .gitkeep тк с ним база не инициализировалась

Это статусный файл, создается при запуске обновления с веб-морды, там лог преобразования, загрузки и прочее


> Ещё вопрос Можно ли использовать не полный дамп а только fb2 дамп

Если не будет какого-то файла, то просто текст не отобразится (и обложка)

> Хорошо бы как то предусмотреть вариант запуска в котором в контейнере только само приложение php а web сервер и база данных используются уже существующие на хосте Возможно в настройки nginx по умолчанию стоит ограничить количество worker до 1го, остальные избыточны(как мне кажется в данном случае)

Когда все это разрабатывалось, так было удобнее, фактически, докер - только для быстрого запуска окружения. Каждый раз собирать контейнер при изменении пары строк было лень.

Количество воркеров - каверы также генерятся, на странице их десятки, так что больше воркеров - шустрее

**Comment by zlsl** [comment]
> В итоге с chmod -R 777 процесс запустился, до этого пытался выдать более конкретные права оказывается оно ещё само gz распаковывает а я думал что дело в этом и распаковал через for f in _.gz ; do gunzip -c "$f" > FlibustaSQL/"${f%._}" ; done

Скрипты в /application/tools должны иметь права на выполнение, из php exec-ом вызываются

**Comment by abubaca4** [comment]
Да выполнение как раз таки было, записи небыло для пользователя под которым оно запускалось

Тогда ещё вопрос, можно как то всё это закрыть паролем чтобы вывешивать в глобальную сеть и без пароля доступа небыло? Или надо http basic auth на веб сервере делать?

**Comment by abubaca4** [comment]
Вроде импортировалось
Поиск конечно работает не лучше чем в MyHomeLib(по имени автора почему то не ищет(или требует чёткую последовательность отчество имя фамилия), но при этом по серии находит и из неё уже можно фильтр по имени автора вызвать)
Но проблема с импортом решилась
Надеюсь что какой то ответ на счёт планов по введению авторизации будет
