### ISSUE TITLE
Не собирается контейнер с php-fpm-8.1 на Synology

### ISSUE THREAD

**Issue by goletsa** [zlsl/flibusta#22]
После обновления до текущей версии перестал собираться контейнер с php
Исходный с 7.2 собирался нормально.

```
# docker-compose build
[+] Building 0.0s (0/0)
[+] Building 0.1s (0/2)
 => [internal] load build definition from Dockerfile                                                                                                               0.1s
[+] Building 0.2s (0/2)
[+] Building 0.9s (0/2)
[+] Building 3.7s (2/3)
[+] Building 6.7s (4/7)
 => [internal] load build definition from Dockerfile                                                                                                               2.2s
[+] Building 8.6s (7/8)
 => [internal] load build definition from Dockerfile                                                                                                               2.2s
 => => transferring dockerfile: 31B                                                                                                                                0.0s
[+] Building 8.9s (7/8)
[+] Building 9.3s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                               2.2s
 => => transferring dockerfile: 31B                                                                                                                                0.0s
[+] Building 12.3s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                               1.6s
 => => transferring dockerfile: 32B                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                  2.7s
 => => transferring context: 2B                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/php:8.1-fpm-alpine                                                                                              3.2s
 => https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions                                                      1.1s
 => [1/5] FROM docker.io/library/php:8.1-fpm-alpine@sha256:473d821f7cff9a5fe8bd2879c69518afdd2a4396c842607bafcf0a1eefa00eb7                                        0.0s
 => CACHED [2/5] ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/        0.0s
 => CACHED [3/5] WORKDIR /application                                                                                                                              0.0s
 => CACHED [4/5] RUN apk --update add postgresql-client;  apk add python3;                                                                                         0.3s
 => ERROR [5/5] RUN install-php-extensions gd bz2 pdo_pgsql                                                                                                        3.4s
------
 > [5/5] RUN install-php-extensions gd bz2 pdo_pgsql:
#0 2.822 /bin/sh: install-php-extensions: Permission denied
```

```
# docker --version
Docker version 20.10.23, build 876964a
# docker-compose --version
Docker Compose version v2.9.0-6413-g38f6acd
```

**Comment by DmitriyStoyanov** [comment]
аналогично столкнулся с этой же проблемой, начал смотреть на другой машине, сначала свалился при сборке с ошибкой:
```
docker-compose build
...
Step 2/5 : ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
the --chmod option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
ERROR: Service 'php-fpm' failed to build : Build failed
```

ок, включил buildkit
```
DOCKER_BUILDKIT=1 docker-compose build
...
 => ERROR [5/5] RUN install-php-extensions gd bz2 pdo_pgsql                                                                             0.3s 
------                                                                                                                                       
 > [5/5] RUN install-php-extensions gd bz2 pdo_pgsql:                                                                                        
#9 0.246 /bin/sh: install-php-extensions: Permission denied                                                                                  
------                                                                                                                                       
executor failed running [/bin/sh -c install-php-extensions gd bz2 pdo_pgsql]: exit code: 126                                                 
ERROR: Service 'php-fpm' failed to build : Build failed
```

**Comment by DmitriyStoyanov** [comment]
если в этом файле https://github.com/zlsl/flibusta/blob/main/phpdocker/php-fpm/Dockerfile
```
ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
```
поменять на
```
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
```
и
```
RUN install-php-extensions gd bz2 pdo_pgsql
```
на
```
RUN chmod +x /usr/local/bin/install-php-extensions; install-php-extensions gd bz2 pdo_pgsql
```

Все заработает, сейчас МР сделаю

**Comment by DmitriyStoyanov** [comment]
Исправление тут - https://github.com/zlsl/flibusta/pull/23

**Comment by zlsl** [comment]
merged

**Comment by DmitriyStoyanov** [comment]
хм, а у меня что-то после обновления на новую версию php:8.1-fpm-alpine и после сборки начинают падать ошибки при открытии библиотеки:
```
Warning: Undefined variable $dbh in /application/modules/primary/index.php on line 190

Fatal error: Uncaught Error: Call to a member function prepare() on null in /application/modules/primary/index.php:190 Stack trace: #0 /application/renderer.php(125): include() #1 /application/public/index.php(148): include('/application/re...') #2 {main} thrown in /application/modules/primary/index.php on line 190
```
причем это не в логах приложения, а непосредственно в интерфейсе:
![image](https://github.com/user-attachments/assets/c53f570d-5aee-4895-846b-c0c321cce0ba)

и при входе на сервис страницу:
```
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /application/modules/service/index.php on line 9

Warning: Undefined variable $dbh in /application/modules/service/index.php on line 22

Fatal error: Uncaught Error: Call to a member function query() on null in /application/modules/service/index.php:22 Stack trace: #0 /application/renderer.php(125): include() #1 /application/public/index.php(148): include('/application/re...') #2 {main} thrown in /application/modules/service/index.php on line 22
```
![image](https://github.com/user-attachments/assets/210ed6ee-9d9f-4182-a93d-b8e631433b56)

**Comment by zlsl** [comment]
> хм, а у меня что-то после обновления на новую версию php:8.1-fpm-alpine и после сборки начинают падать ошибки при открытии библиотеки:
> 
> ```
> Warning: Undefined variable $dbh in /application/modules/primary/index.php on line 190
> 
> Fatal error: Uncaught Error: Call to a member function prepare() on null in /application/modules/primary/index.php:190 Stack trace: #0 /application/renderer.php(125): include() #1 /application/public/index.php(148): include('/application/re...') #2 {main} thrown in /application/modules/primary/index.php on line 190
> ```
> 
> причем это не в логах приложения, а непосредственно в интерфейсе: ![image](https://private-user-images.githubusercontent.com/1244213/374628652-c53f570d-5aee-4895-846b-c0c321cce0ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDI0ODksIm5iZiI6MTcyODQwMjE4OSwicGF0aCI6Ii8xMjQ0MjEzLzM3NDYyODY1Mi1jNTNmNTcwZC01YWVlLTQ4OTUtODQ2Yi1jMGMzMjFjY2UwYmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMTU0MzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI4ZWY0OGZlY2QzZmQxODU2NWI3NmMxMWMxNzVmNjE4ODgzOGZjMDZhMWVmM2M3OTIyZjNhYWQ4MGRmMDQ2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bzjTyFpgBKAWAKUJknjvUk18zoh3i7Re6tAUn-8Oyiw)
> 
> и при входе на сервис страницу:
> 
> ```
> Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /application/modules/service/index.php on line 9
> 
> Warning: Undefined variable $dbh in /application/modules/service/index.php on line 22
> 
> Fatal error: Uncaught Error: Call to a member function query() on null in /application/modules/service/index.php:22 Stack trace: #0 /application/renderer.php(125): include() #1 /application/public/index.php(148): include('/application/re...') #2 {main} thrown in /application/modules/service/index.php on line 22
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/1244213/374629174-210ed6ee-9d9f-4182-a93d-b8e631433b56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDI0ODksIm5iZiI6MTcyODQwMjE4OSwicGF0aCI6Ii8xMjQ0MjEzLzM3NDYyOTE3NC0yMTBlZDZlZS05ZDlmLTQxODItYTkzZC1iOGU2MzE0MzNiNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMTU0MzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRkMGUzYzA0YjdkZDY1MGU2OTg2NDFhYTJiNjAyNGExNzIwMTNlNjYwNzk1N2MyNjQyY2U4ZGY5Y2QyZjIzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tQZngERGQmNDOON6fiYKWMFAFwcf11ch7A4M0n3GjKc)

$dbh - handler соединения с БД. Какая-то проблема с соединением

**Comment by goletsa** [comment]
> Warning: Undefined variable $dbh in /application/modules/primary/index.php on line 190

https://github.com/zlsl/flibusta/blob/4dac3aa20f145fcefa5467d808c7966c5830f92f/application/init.php#L18
Там что-то с кодом получения dbpasswd, пока локально тестирую так:
```
$dbpasswd = getenv('FLIBUSTA_DBPASSWORD')?getenv('FLIBUSTA_DBPASSWORD'):'flibusta';
```
И строка конекта к базе кривая, dbhost + хардкод.
https://github.com/zlsl/flibusta/blob/4dac3aa20f145fcefa5467d808c7966c5830f92f/application/init.php#L27


Так же падает с ошибкой ZipArchive (добавил zip в список расширений).

Ну и еще ошибок после перехода на 8.1, на странице сервиса
```
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /application/modules/service/index.php on line 9
```

UPD:
И обложки перестали грузиться похоже.

**Comment by DmitriyStoyanov** [comment]
db url пофиксал тут - https://github.com/zlsl/flibusta/pull/24

**Comment by DmitriyStoyanov** [comment]
еще PR #25 для фикса ошибки trim функции на service/index.php

**Comment by DmitriyStoyanov** [comment]
ох, даже после этого нажимаешь кнопку "Обновить базу" и снова ошибка
`Warning: Cannot modify header information - headers already sent by (output started at /application/renderer.php:1) in /application/modules/service/index.php on line 56`

да уж обновление php это не просто так сменить версию файле :)

**Comment by zlsl** [comment]
> да уж обновление php это не просто так сменить версию файле :)

Да, многое deprecated, вызовы чуть другие.

**Comment by DmitriyStoyanov** [comment]
что-то и сам импорт внутри не пашет, пробую запустить 
```shell
docker exec -ti flibusta_php-fpm_1 /bin/sh
/application # /application/tools/app_import_sql.sh
...
lib.a.annotations_pics.sql
libapics
  File "/application/tools/app_db_converter.py", line 93
    print "\n ! Unknown line in main body: %s" % line
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
psql: error: /application/sql/psql/lib.a.annotations_pics.sql: No such file or directory
lib.b.annotations_pics.sql
libbpics
  File "/application/tools/app_db_converter.py", line 93
    print "\n ! Unknown line in main body: %s" % line
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
psql: error: /application/sql/psql/lib.b.annotations_pics.sql: No such file or directory
lib.a.annotations.sql
libaannotations
  File "/application/tools/app_db_converter.py", line 93
    print "\n ! Unknown line in main body: %s" % line
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
psql: error: /application/sql/psql/lib.a.annotations.sql: No such file or director
...
lib.reviews.sql
libreviews
  File "/application/tools/app_db_converter.py", line 93
    print "\n ! Unknown line in main body: %s" % line
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
psql: error: /application/sql/psql/lib.reviews.sql: No such file or directory
INSERT 0 0
INSERT 0 0
INSERT 0 0
...
[d.fb2-009373-367300]

[f.fb2-794181-797606]
[d.fb2-172703-173908]
[f.fb2-787400-791175]
[f.fb2-791176-794180]
[f.fb2-173909-177717]
[f.fb2-177718-183065]
...
```
и соответственно архивы распакованные остались, а файлов в FlibustaSQL/psql каталоге не появилось. Ну и соответственно в библиотеке 0 книг

**Comment by DmitriyStoyanov** [comment]
там похоже python 2 сменился на python 3, сейчас фикс локально готовлю, проверю, сделаю еще PR для этой части

**Comment by DmitriyStoyanov** [comment]
print пофиксал, дальше фейлит
```
/application/tools/app_db_converter.py:110: SyntaxWarning: invalid escape sequence '\w'
  extra = re.sub("CHARACTER SET [\w\d]+\s*", "", extra.replace("unsigned", ""))
/application/tools/app_db_converter.py:111: SyntaxWarning: invalid escape sequence '\w'
  extra = re.sub("COLLATE [\w\d]+\s*", "", extra.replace("unsigned", ""))
Line 1 (of 3: 33.33%) [0 tables] [0 inserts] [ETA: 0 min 0 sec]Traceback (most recent call last):
  File "/application/tools/app_db_converter.py", line 228, in <module>
    parse(sys.argv[1], sys.argv[2])
  File "/application/tools/app_db_converter.py", line 72, in parse
    line = line.decode("utf8").strip().replace(r"\\", "WUBWUBREALSLASHWUB").replace(r"\'", "''").replace("WUBWUBREALSLASHWUB", r"\\")
           ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
```

Что-то не все так просто после залетает

**Comment by zlsl** [comment]
> Что-то не все так просто после залетает

line.decode("utf8")  - это из python 2.x кажется. 3.х уже с поддержкой utf-8. Не помню уже эту заморочку, сталкивался

**Comment by DmitriyStoyanov** [comment]
python код пофиксал в #26 
Теперь можно хоть локально базу импортнуть через скрипт в контейнере

**Comment by DmitriyStoyanov** [comment]
также фикс отсутствия zip расширения для php тут - https://github.com/zlsl/flibusta/pull/27

**Comment by blitvin** [comment]
Извините, что так криво  получилось  - я никогда раньше  с php не  имел дела - а в java с backward compatibility проще .. Так что вышло по Черномырдину - хотел как лучше..

**Comment by DmitriyStoyanov** [comment]
у всех бывает, когда обновляешь версии, думаешь в одном месте что-то улучшить, а получаешь много чего отваливающегося. Обычно это замечается на фазе тестирования, кода она есть. В более крупных проектах думаю уже бы добавили, а тут имеем что имеем. Надо подумать о каких-то линтах как минимум наверное и добавить их в автотесты, чтоб проблемы которые отхватили на python 2->3 были видны. Для php наверное тоже можно что-то поискать

**Comment by DmitriyStoyanov** [comment]
добавил туда же в PR #27 еще фиксы по отображению картинок для книг по ошибкам которые отлавливал

**Comment by zlsl** [comment]
Вообщем в php:8.1-fpm-alpine нет утилитки stdbuf, поэтому и не запускаются потоки

**Comment by DmitriyStoyanov** [comment]
Т.е. только нужно добавить пакет этот?
https://command-not-found.com/stdbuf

**Comment by zlsl** [comment]
> Т.е. только нужно добавить пакет этот?

Все, есть коммит с исправлениями. Также надо чтобы права на FlibustaSQL и вложенный папки были на запись

**Comment by DmitriyStoyanov** [comment]
после всех исправлений собрал на своей synology, кстати интересно что там импорт БД занимает аж целый час, нужно посмотреть что можно улучшить в этой части. Но я не об этом

Начал смотреть списки книг + подключил opds, и опять же встречаются ошибки 

```
2024/10/09 18:57:52 | stderr | NOTICE: PHP message: PHP Warning:  Attempt to read property "filename" on bool in /application/public/extract_cover.php on line 102
2024/10/09 18:57:52 | stderr | 172.21.0.4 -  09/Oct/2024:15:57:52 +0000 "GET /extract_cover.php" 500
2024/10/09 18:57:52 | stderr | NOTICE: PHP message: PHP Fatal error:  Uncaught ValueError: Invalid or uninitialized Zip object in /application/public/extract_cover.php:117
2024/10/09 18:57:52 | stderr | Stack trace:
2024/10/09 18:57:52 | stderr | #0 /application/public/extract_cover.php(117): ZipArchive->getFromName('801520.fb2')
2024/10/09 18:57:52 | stderr | #1 {main}
-- | -- | --
2024/10/09 18:57:52 | stderr | thrown in /application/public/extract_cover.php on line 117
```

**Comment by zlsl** [comment]
> Начал смотреть списки книг + подключил opds, и опять же встречаются ошибки

Права на запись у ./cache есть?

Если есть, то возможно не построился индекс архивов, через сервис - Сканирование ZIP, потом принудительно обновить страницу

**Comment by zlsl** [comment]
Собственно ошибка

`2024/10/09 18:57:52 | stderr | NOTICE: PHP message: PHP Warning:  Attempt to read property "filename" on bool in /application/public/extract_cover.php on line 102
`

Из за того, что в
`$stmt = $dbh->prepare("SELECT * FROM book_zip WHERE $id BETWEEN start_id AND end_id AND usr=$u");
$stmt->execute();
$zip_name = $stmt->fetch()->filename;`

Не получено имя файла с индексом книги

**Comment by DmitriyStoyanov** [comment]
права на запись есть, часть картинок нормально отрабатывает и показывает, в каталоге cache/authors и cache/covers уже много картинок, но иногда фейлится с этой ошибкой

**Comment by DmitriyStoyanov** [comment]
еще одна ошибка
`NOTICE: PHP message: PHP Warning:  file_get_contents(none.jpg): Failed to open stream: No such file or directory in /application/public/extract_cover.php on line 149`
видимо связана с тем что там нет этого none.jpg файла для отображения когда картинки не обнаружено в книге

**Comment by zlsl** [comment]
> еще одна ошибка `NOTICE: PHP message: PHP Warning: file_get_contents(none.jpg): Failed to open stream: No such file or directory in /application/public/extract_cover.php on line 149` видимо связана с тем что там нет этого none.jpg файла для отображения когда картинки не обнаружено в книге

Исправил на полный путь к картинке пустой обложки

**Comment by DmitriyStoyanov** [comment]
ну что, эту ишую наверное можно закрывать, основное что было, закрыли вроде
