### ISSUE TITLE
Ошибка 

### ISSUE THREAD

**Issue by artemsmit** [zlsl/flibusta#30]
Все сделал четко по инструкции, при нажатии кнопки "Обновить" выдает  в веб-интерфейсе следующее: 

Warning: Cannot modify header information - headers already sent by (output started at /application/renderer.php:1) in /application/modules/service/index.php on line 61

В чем может быть проблема?

**Comment by DmitriyStoyanov** [comment]
проблема в связи с обновлением php, и дискуссия здесь еще идет
https://github.com/zlsl/flibusta/issues/22

Пока пофиксана работа импорта библиотеки с помощью внутреннего скрипта, т.е. если запустить локально

```shell
docker exec -ti flibusta_php-fpm_1 /bin/sh
/application # /application/tools/app_import_sql.sh
```
