### ISSUE TITLE
Потеряли скачивание архивов f.n.

### ISSUE THREAD

**Issue by goletsa** [zlsl/flibusta#32]
> grep -Eo 'href="f\.(fb2|n)\.[0-9\-]+\.zip"' page.html | sed 's/href="//;s/"//' > links.txt
> 
> 
> 
> Потеряли скачивание f.n.XXXXX архивов 

 _Originally posted by @goletsa in [5c03069](https://github.com/zlsl/flibusta/commit/5c03069b431b92db87ce8085965233e91a9435fa#r147789446)_

**Comment by zlsl** [comment]
принято
