### ISSUE TITLE
OPDS: Ошибки в каталоге авторов

### ISSUE THREAD

**Issue by AlexeyTorch** [zlsl/flibusta#36]
1. При попытке  зайти в автора на букву вместо списка авторов выдается набор книг начинающихся на нее
2. При попытке скачать книгу получаем ошибку 500

Вторая проблема лечится заменой в /application/opds/search_book.php

```
        echo "<link rel='http://opds-spec.org/image/thumbnail' href='http://192.168.32.5/lib/get_cover.php?id=$b->bookid' type='image/jpeg'/>";
        echo "<link rel='http://opds-spec.org/image' href='http://192.168.32.5/lib/get_cover.php?id=$b->bookid' type='image/jpeg'/>";
        echo " <link href='http://192.168.32.5/lib/get_fb2.php?id=$b->bookid' rel='http://opds-spec.org/acquisition/open-access' type='application/fb2+zip' />";
```
на 
```
        echo "<link rel='http://opds-spec.org/image/thumbnail' href='/extract_cover.php?id=$b->bookid' type='image/jpeg'/>";
        echo "<link rel='http://opds-spec.org/image' href='/extract_cover.php?id=$b->bookid' type='image/jpeg'/>";
        echo " <link href='/fb2.php?id=$b->bookid' rel='http://opds-spec.org/acquisition/open-access' type='application/fb2+zip' />";

```
но на понять как править запрос я пока не смог

**Comment by DmitriyStoyanov** [comment]
хм, он не заходит в фай search_author.php
т.е. попадая в 
https://github.com/zlsl/flibusta/blob/main/application/opds/search.php
```php
<?php

switch ($url->action) {
	case 'author':
		include('search_author.php');
		break;

	default:
		include('search_book.php');
}
?>
```
он не попадает в search_author.php потому как при таком урле
/opds/search/author?q=z
у него action = search

выяснил добавив дебаг
error_log("Action value: " . $url->action);

осталось понять как проваливаться, чтоб action=author а не search


попытался вывести все параметры в $url

http://localhost:27100/opds/search/author?q=z
```
php-fpm-1    | NOTICE: PHP message: stdClass Object
php-fpm-1    | (
php-fpm-1    |     [mod] => opds
php-fpm-1    |     [action] => search
php-fpm-1    |     [var1] => 0
php-fpm-1    |     [var2] => 0
php-fpm-1    |     [var3] => 0
php-fpm-1    |     [title] => 
php-fpm-1    |     [description] => 
php-fpm-1    |     [mod_path] => /application/modules/opds/
php-fpm-1    |     [mod_menu] => 
php-fpm-1    |     [image] => 
php-fpm-1    |     [noindex] => 0
php-fpm-1    |     [index] => 1
php-fpm-1    |     [follow] => 1
php-fpm-1    |     [module_menu] => 
php-fpm-1    |     [js] => Array
php-fpm-1    |         (
php-fpm-1    |         )
php-fpm-1    |     [editor] => 0
php-fpm-1    |     [access] => 0
php-fpm-1    |     [canonical] => 
php-fpm-1    |     [module] => /application/modules/opds/index.php
php-fpm-1    | )
```

**Comment by zlsl** [comment]
`        echo " <link href='http://192.168.32.5/lib/get_fb2.php?id=$b->bookid' rel='http://opds-spec.org/acquisition/open-access' type='application/fb2+zip' />";
`

Прописан ip внутренний.

**Comment by DmitriyStoyanov** [comment]
да, эту часть уже изменил локально, и нашел кстати вариант как провалиться в search_author
```php
<?php
$search = $_GET['by'];
switch ($search) {
	case 'author':
		include('search_author.php');
		break;

	default:
		include('search_book.php');
}
?>
```
поменяв урл на 
http://localhost:27100/opds/search?by=author&q=b

но дальше там тоже фейлы в search_author.php
сначала было
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: PDOStatement::bindParam(): Argument #2 ($var) cannot be passed by reference in /application/opds/search_author.php:37
эту часть пофиксал
сейчас падает на
```
postgres-1   | 2024-10-11 08:46:26.937 UTC [57] ERROR:  operator does not exist: character = integer at character 78
postgres-1   | 2024-10-11 08:46:26.937 UTC [57] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
postgres-1   | 2024-10-11 08:46:26.937 UTC [57] STATEMENT:  SELECT *, 
postgres-1   |                  (SELECT COUNT(*) FROM libavtor, libbook WHERE 
postgres-1   |                  libbook.deleted=0 AND
postgres-1   |                  libbook.BookId=libavtor.BookId AND
postgres-1   |                  libavtor.AvtorId=libavtorname.AvtorId AND
postgres-1   |                  libavtor.avtorId=libavtorname.AvtorId) cnt 
postgres-1   |                  FROM libavtorname
postgres-1   |                          LEFT JOIN libapics USING(AvtorId)
postgres-1   |                  WHERE LastName LIKE $1 ORDER BY LastName, FirstName
php-fpm-1    | NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: character = integer
php-fpm-1    | LINE 3:   libbook.deleted=0 AND
php-fpm-1    |                          ^
php-fpm-1    | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. in /application/opds/search_author.php:39
php-fpm-1    | Stack trace:
php-fpm-1    | #0 /application/opds/search_author.php(39): PDOStatement->execute()
php-fpm-1    | #1 /application/opds/search.php(5): include('/application/op...')
php-fpm-1    | #2 /application/opds/index.php(26): include('/application/op...')
php-fpm-1    | #3 /application/public/index.php(147): include('/application/op...')
php-fpm-1    | #4 {main}
php-fpm-1    |   thrown in /application/opds/search_author.php on line 39
php-fpm-1    | 172.18.0.3 -  11/Oct/2024:08:46:26 +0000 "GET /index.php" 500
```

**Comment by zlsl** [comment]
`libbook.deleted='0'` надо сделать
Там CHAR тип

**Comment by DmitriyStoyanov** [comment]
могу свои пока наработки выгрузить в МР, но там еще не до конца готово, нужно еще доделывать, Но уже хоть квери работают, а формирует пока недостаточно правильный opds. Либо опять же когда позже будет время продолжить допиливание и тесты

**Comment by DmitriyStoyanov** [comment]
https://github.com/zlsl/flibusta/pull/37 тут пока закоммитал что исправил
список авторов только по алфавиту, плюс пофиксал запросы, чтоб поиск по автору по первой букве. Но что-то в выводе нет ссылок в коде. их и раньше не было, поэтому эту часть еще нужно дописать

**Comment by artemsmit** [comment]
А нельзя ли всю эту историю в контейнеры запихнуть и на dockerhub загрузить чтоб не собирать каждый раз?

**Comment by AlexeyTorch** [comment]
> #37 тут пока закоммитал что исправил
> список авторов только по алфавиту, плюс пофиксал запросы, чтоб поиск по автору по первой букве. Но что-то в выводе нет ссылок в коде. их и раньше не было, поэтому эту часть еще нужно дописать


На андроиде FB Reader выдает  пустую  страницу автора,  AlReaderX падает

**Comment by DmitriyStoyanov** [comment]
> А нельзя ли всю эту историю в контейнеры запихнуть и на dockerhub загрузить чтоб не собирать каждый раз?

Я сам собирался это предложить, когда дофиксаем то, что не работает.

**Comment by DmitriyStoyanov** [comment]
https://github.com/zlsl/flibusta/pull/38
Добил вроде список по авторам

**Comment by DmitriyStoyanov** [comment]
ну вроде как все, ишуя закрыта
