### ISSUE TITLE
Ошибки на странице Полка

### ISSUE THREAD

**Issue by DmitriyStoyanov** [zlsl/flibusta#45]
При входе на страницу Полка - /fav/
Если еще этих полок не создано, вылетает эксепшн:

`PDOException Object ( [message:protected] => SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type uuid: "" [string:Exception:private] => [code:protected] => 22P02 [file:protected] => /application/modules/fav/index.php [line:protected] => 38 [trace:Exception:private] => Array ( [0] => Array ( [file] => /application/modules/fav/index.php [line] => 38 [function] => execute [class] => PDOStatement [type] => -> [args] => Array ( ) ) [1] => Array ( [file] => /application/renderer.php [line] => 125 [args] => Array ( [0] => /application/modules/fav/index.php ) [function] => include ) [2] => Array ( [file] => /application/public/index.php [line] => 149 [args] => Array ( [0] => /application/renderer.php ) [function] => include ) ) [previous:Exception:private] => [errorInfo] => Array ( [0] => 22P02 [1] => 7 [2] => ERROR: invalid input syntax for type uuid: "" ) )`

и в логах соответственно:
```
NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type uuid: "" in /application/modules/fav/index.php:56
Stack trace:
#0 /application/modules/fav/index.php(56): PDOStatement->execute()
#1 /application/renderer.php(125): include('/application/mo...')
#2 /application/public/index.php(149): include('/application/re...')
#3 {main}
  thrown in /application/modules/fav/index.php on line 56
```

**Comment by zlsl** [comment]
fixed
[50f7c5b4b89a9e4410700a650376d0f42df1afd0](https://github.com/zlsl/flibusta/commit/50f7c5b4b89a9e4410700a650376d0f42df1afd0)
