### ISSUE TITLE
игнорирование архива d.fb2-009373-367300.zip  

### ISSUE THREAD

**Issue by djp1-hub** [zlsl/flibusta#6]
Коллега! а в чем смысл пропуска арихва  d.fb2-009373-367300.zip   вот этим условием?
			if (strpos($entry, "d.fb2-009") !== false) {

**Comment by zlsl** [comment]
> Коллега! а в чем смысл пропуска арихва d.fb2-009373-367300.zip вот этим условием? if (strpos($entry, "d.fb2-009") !== false) {

Это лет 10 назад было, скорее всего либо дубли ID были в других архивах. А сам архив мелкий, его отбросил.
