### ISSUE TITLE
Не работает поиск в OPDS

### ISSUE THREAD

**Issue by goletsa** [zlsl/flibusta#7]
При подключении OPDS каталога в FBReader вообще не работает поиск.

При попытке посмотреть список авторов падает с ошибкой работы с DB.
```
flibusta-php-fpm-1
date,stream,content
2024/09/28 13:11:46,stderr,172.25.0.4 -  28/Sep/2024:10:11:46 +0000 "GET /index.php" 500

2024/09/28 13:11:46,stderr,  thrown in /application/opds/authorsindex.php on line 10

2024/09/28 13:11:46,stderr,#2 {main}

2024/09/28 13:11:46,stderr,#1 /application/public/index.php(141): include('/application/op...')

2024/09/28 13:11:46,stderr,#0 /application/opds/index.php(7): include()

2024/09/28 13:11:46,stderr,Stack trace:

2024/09/28 13:11:46,stderr,NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Class 'DB' not found in /application/opds/authorsindex.php:10

2024/09/28 13:11:43,stderr,172.25.0.4 -  28/Sep/2024:10:11:43 +0000 "GET /index.php" 200
```

И не ясно как работает функционал книжкой полки, она вроде есть но как туда что-то добавить не увидел.

**Comment by zlsl** [comment]
После создания "полки" - нажать на ее имя (синее в списке), в верхнем углу появится вместо "Книжные полки" имя текущей выбранной

Далее, в книжную полку можно добавить:
1. Книгу (Сердечко под  обложкой)
2. Серию книг (Будет кнопка в списке книг серии "Имя серии в избранное")
3. Автора (Со страницы автора кнопка "В избранное")

**Comment by zlsl** [comment]
В OPDS по авторам - там еще кусок старых функция работы с БД, переделаю.
OPDS был давно заброшен, т.к. устройства закончились

**Comment by DmitriyStoyanov** [comment]
Судя по всему везде где встречается DB::query в коде нужно переделать на новый подход, т.е. в 4х местах:
https://github.com/zlsl/flibusta/blob/54aca43026a56ede0c34dbc0b06d287bab861d37/application/opds/search_book.php#L19
https://github.com/zlsl/flibusta/blob/54aca43026a56ede0c34dbc0b06d287bab861d37/application/opds/authorsindex.php#L10
https://github.com/zlsl/flibusta/blob/54aca43026a56ede0c34dbc0b06d287bab861d37/application/opds/search_author.php#L31
https://github.com/zlsl/flibusta/blob/54aca43026a56ede0c34dbc0b06d287bab861d37/application/opds/search_author.php#L59

**Comment by zlsl** [comment]
Да, также там функция другая получения следующей записи

**Comment by goletsa** [comment]
> Далее, в книжную полку можно добавить:
> 
> 1. Книгу (Сердечко под  обложкой)
> 2. Серию книг (Будет кнопка в списке книг серии "Имя серии в избранное")
> 3. Автора (Со страницы автора кнопка "В избранное")

В OPDS отдает только одиночные книги.
Добавил автора и серию - не отображает.

**Comment by blitvin** [comment]
Я сделал pull request с фиксами для opds, у меня вроде бы ошибки в php сиязанные с базой данных в скриптах opds ушли.. вроде работает

**Comment by goletsa** [comment]
> Я сделал pull request с фиксами для opds, у меня вроде бы ошибки в php сиязанные с базой данных в скриптах opds ушли.. вроде работает

Я попробовал заменить 3 файла из реквеста, как была 500 так и осталась.

**Comment by blitvin** [comment]
А что в логах? Какие ошибки?

**Comment by blitvin** [comment]
Я сделал новый коммит - то что я видел у себя - какой то странный конфликт между парсером php и xml - ошибка синтаксиса в первой строке . А строка - заголовок  <?xml ...> ...

**Comment by blitvin** [comment]
Надо сказать, я в некоторой растерянности по поводу opds  - с одной стороны есть люди у которых как минимум часть вещей в работает. С другой, я натыкаюсь на вещи которые работать в принципе не могут, типа неправильный тип в  сравнении в  search_books.php - > where deleted=0 , но  deleted объявлен как char(1) , и  postgres просто выбрасывает exception ... когда я делал PR , все что я надеялся сделать - заменить старые вызовы на PDO API .. и в первом  commit было только это.. Затем проявились другие проблемы.. Я надеюсь в конце концов побороть их, и заставить opds работать. Просто я никогда раньше не имел дела с php, может быть я что то кардинальное упускаю?

**Comment by goletsa** [comment]
Судя по всему его никто не тестировал или может быть от клиента зависит. Я использую для тестов FBReader (Windows/Android).

**Comment by DmitriyStoyanov** [comment]
протестировал мр #15
часть функционала работает, отдается список новинок, выгребает картинки в списке книг, выкачивает книги: по жанрам также работает функционал

Список по авторам показывает, но при этом провалиться в любую букву не дает
`2024/10/07 16:55:05 [error] 31#31: *399 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined property: stdClass::$keywords in /application/modules/404/module.conf on line 3" while reading response header from upstream, client: 192.168.0.106, server: , request: "GET /authorsindex/Q HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "192.168.0.121:27100"`

При запросе "по сериям", также ошибка:
`2024/10/07 16:56:58 [error] 29#29: *57 FastCGI sent in stderr: "PHP message: PHP Warning:  include(sequencesindex.php): failed to open stream: No such file or directory in /application/opds/index.php on line 10PHP message: PHP Warning:  include(): Failed opening 'sequencesindex.php' for inclusion (include_path='.:/usr/share/php') in /application/opds/index.php on line 10" while reading response header from upstream, client: 192.168.0.106, server: , request: "GET /opds/sequencesindex HTTP/1.1", upstream: "fastcgi://172.21.0.4:9000", host: "192.168.0.121:27100"`

И при запуске поиска:
```
webserver_1  | 2024/10/07 16:58:38 [error] 29#29: *60 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'DB' not found in /application/opds/search_book.php:17
webserver_1  | Stack trace:
webserver_1  | #0 /application/opds/search.php(9): include()
webserver_1  | #1 /application/opds/index.php(25): include('/application/op...')
webserver_1  | #2 /application/public/index.php(146): include('/application/op...')
webserver_1  | #3 {main}
webserver_1  |   thrown in /application/opds/search_book.php on line 17" while reading response header from upstream, client: 192.168.0.106, server: , request: "GET /opds/search?q=%D0%BD%D0%B0%D0%B7%D0%B0%D0%B4+%D0%B2+%D0%B1%D1%83%D0%B4%D1%83%D1%89%D0%B5%D0%B5 HTTP/1.1", upstream: "fastcgi://172.21.0.4:9000", host: "192.168.0.121:27100"
```

**Comment by DmitriyStoyanov** [comment]
вообще нужно сам каталог opds немного подправить
При добавлении библиотеки в читалку по урлу /opds, нет никакой информации о каталоге, соответственно ошибки в приложении возникают, которые ты просто пропускаешь и добавляешь мануально библиотеку.
По сути нужно добавить то что описано в спецификации opds
Сами спецификации доступны тут - https://github.com/opds-community/specs
можно как пример глянуть что открывается при открытии сейчас в приложении по урлу /opds/ и как пример открыв https://flibusta.is/opds

**Comment by zlsl** [comment]
> Судя по всему его никто не тестировал или может быть от клиента зависит. Я использую для тестов FBReader (Windows/Android).

Да, реализация в клиентах различная, в коде уже есть хаки чтобы работало. Но по стандарту OPDS ни один клиент не работает, везде есть нюансы.

**Comment by zlsl** [comment]
> вообще нужно сам каталог opds немного подправить При добавлении библиотеки в читалку по урлу /opds, нет никакой информации о каталоге, соответственно ошибки в приложении возникают, которые ты просто пропускаешь и добавляешь мануально библиотеку. По сути нужно добавить то что описано в спецификации opds Сами спецификации доступны тут - https://github.com/opds-community/specs можно как пример глянуть что открывается при открытии сейчас в приложении по урлу /opds/ и как пример открыв https://flibusta.is/opds

Как выше писал, если четко по стандарту сделать, то ни одна читалка не работает.

**Comment by blitvin** [comment]
Я извиняюсь, но только сейчас сделал commit с новыми исправлениями для opds , включая fixы ошибки упомянутые в этом треде... не успел до merge.
Пришлось убрать поиск по сериям т.к. скрипта sequencesindex.php нет..

**Comment by blitvin** [comment]
Нужно временно убрать опцию поиска по сериям т.к. не существует opds/sequencesindex.php.

**Comment by DmitriyStoyanov** [comment]
сейчас пробую протестировать поиск через opds, он также не работает:
```
2024/10/09 22:10:07	stderr	NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42803]: Grouping error: 7 ERROR:  column "libbook.filesize" must appear in the GROUP BY clause or be used in an aggregate function
2024/10/09 22:10:07	stderr	172.21.0.4 -  09/Oct/2024:19:10:07 +0000 "GET /index.php" 500
2024/10/09 22:10:07	stderr	LINE 1: SELECT DISTINCT *, libbook.Title BookTitle,
2024/10/09 22:10:07	stderr	                        ^ in /application/opds/search_book.php:32
2024/10/09 22:10:07	stderr	Stack trace:
2024/10/09 22:10:07	stderr	#0 /application/opds/search_book.php(32): PDOStatement->execute()
2024/10/09 22:10:07	stderr	#1 /application/opds/search.php(9): include('/application/op...')
2024/10/09 22:10:07	stderr	#2 /application/opds/index.php(26): include('/application/op...')
2024/10/09 22:10:07	stderr	#3 /application/public/index.php(147): include('/application/op...')
2024/10/09 22:10:07	stderr	#4 {main}
2024/10/09 22:10:07	stderr	  thrown in /application/opds/search_book.php on line 32
```

**Comment by DmitriyStoyanov** [comment]
при поиске по авторам, во первых в логах
`NOTICE: PHP message: PHP Warning:  Undefined property: stdClass::$aplha in /application/opds/authorsindex.php on line 17`

https://github.com/zlsl/flibusta/blob/b6d0775d2aec5e87ce7d87a207a509f696e3a15f/application/opds/authorsindex.php#L17

тут нужно изменить aplha на alpha


но это все равно не помогает, дальше все равно не ищутся авторы

**Comment by DmitriyStoyanov** [comment]
ошибка с aplha ушла, но провалиться дальше по букве в автора не удается, 404-ую ошибку генерит

кажется поднял, там неверная ссылка дальше выходит
к примеру
/authorsindex/u
вместо
/opds/authorsindex/u

Сейчас еще один ПР подготовлю

**Comment by DmitriyStoyanov** [comment]
хотя не сейчас, там еще много неверных урлов получается нужно менять, так что когда будет чуть больше свободного времени локально потестировать

**Comment by DmitriyStoyanov** [comment]
локально протестал, там даже если исправить урл с /authorindex на /opds/authroindex 404-ые уходят, но при этом он циклично видит список авторов по первой букве, т.е. дальше не проваливается, а открывает ту же страницу со всем алфавитом по первой букве (кстати там кроме алфавита множество символов типа "#(*+,-.>?@[\-{' ..., возможно нужно сделать фильтр только по буквам алфавита)

**Comment by blitvin** [comment]
Я opds/authorsindex.php пытался изменить, но моего убогого знания php не хватает чтобы во первых фильтровать юникод ( пытался md_ord сравнивать с 1040 .. 1105 , получаю ерунду ) но главное он игнорирует букву которую получает по href - кстати в не хватает префикса /opds  - должно быть
<pre>echo &quot;&lt;link href=&apos;/opds/authorsindex/$ach-&gt;alpha&apos; type=&apos;application/atom+xml;profile=opds-catalog&apos; /&gt;&quot;;</pre>
Так что он не зацикливается, просто не обрабатывает первыю букву автора.
По поводу откуда берутся не буквы в том что  query возвращает - может ли быть что возвращается только частичный code point первой буквы - и тогда если ето английский - все нормально, если нет то получается мусор?

**Comment by DmitriyStoyanov** [comment]
в самом authorindex селект устроен так, что ищет только по первой букве фамилии
https://github.com/zlsl/flibusta/blob/e0e7ead88cc61fdeb21ef2ba2989c780afd147ee/application/opds/authorsindex.php#L14

Так что дальше он должен идти уже на другую страницу, той что еще нет
Ну или можно конечно отправить на search_author.php за неимением другой
Но лучше конечно сделать все же наподобии того, как сделано с жанрами
сначала идет в  genres.php с запросом:
```php
$gs = $dbh->prepare("SELECT DISTINCT(genremeta) genre FROM libgenrelist ORDER BY genre");
```
затем отсылает пользователя в listgenres.php
```php
echo " <link href='/opds/listgenres/?id=" . urlencode($g->genre) . "' type='application/atom+xml;profile=opds-catalog' />";
```

где идет уже другой запрос - 
```php
$gs = $dbh->prepare("SELECT *,
	(SELECT COUNT(*) FROM libgenre WHERE libgenre.genreid=g.genreid) cnt
	FROM libgenrelist g
	WHERE g.genremeta=:id");
$gs->bindParam(":id", $_GET['id']);
$gs->execute();
```

**Comment by DmitriyStoyanov** [comment]
сделал перенаправление на /opds/search/author в #35

**Comment by DmitriyStoyanov** [comment]
что-то при этом в поиске выдается список книг в которых содержится указанная буква, а не в которых автор с этой буквой
Надо посмотреть вообще какие-то варианты где-то может есть? вообще может какие-то внешние фреймворки можно заюзать, типа https://github.com/kiwilan/php-opds

**Comment by zlsl** [comment]
> что-то при этом в поиске выдается список книг в которых содержится указанная буква, а не в которых автор с этой буквой
> Надо посмотреть вообще какие-то варианты где-то может есть? вообще может какие-то внешние фреймворки можно заюзать, типа https://github.com/kiwilan/php-opds

Завтра приведу в порядок opds.

**Comment by DmitriyStoyanov** [comment]
ишую можно закрывать
